import { useEffect, useRef, useState } from 'react';
import io from 'socket.io-client';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

class Message {
	constructor(message, joined = false) {
		this.message = message;
		this.id = Date.now();
		this.type = joined ? 'info' : 'message';
	}
}

export default function Home() {
	const [messages, setMessages] = useState([]);
	const [message, setMessage] = useState('');
	const ioRef = useRef();

	const sendMessage = () => {
		ioRef.current.emit('message', message);
	};

	useEffect(() => {
		ioRef.current = io();

		ioRef.current.on('joined', message => {
			setMessages(existingMessages => [
				...existingMessages,
				new Message(message, true),
			]);
		});

		ioRef.current.on('message', message => {
			setMessages(existingMessages => [
				...existingMessages,
				new Message(message),
			]);
		});

		return () => ioRef.current.disconnect();
	}, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<ul>
					{messages.map(m => (
						<li key={m.id}>{m.message}</li>
					))}
				</ul>
				<input
					type='text'
					value={message}
					onChange={e => setMessage(e.target.value)}
				/>
				<button onClick={sendMessage}>Send</button>
			</main>

			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image
							src='/vercel.svg'
							alt='Vercel Logo'
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
	);
}
